In [1]:
import pandas as pd
import numpy as np

# DF 구경하기

In [2]:
df = pd.read_csv("C:\\Users\\kim a hyun\\Desktop\\사고다발지현황.csv",encoding='cp949')
type(df)

pandas.core.frame.DataFrame

In [3]:
df

,시군명,사고년도,사고유형구분,다발지식별자,다발지역그룹식별자,법정동코드,위치코드,시도시군구명,사고지역위치명,발생건수,사상자수,사망자수,중상자수,경상자수,부상자수,위도,경도,사고다발지역폴리곤정보
0,가평군,2018,보행노인사고다발지,6506068,2019036,4182032521,41820001,경기도 가평군1,경기도 가평군 청평면(청평터미널 부근),4,4,0,2,2,0,37.739333,127.421720,"{""type"":""Polygon"",""coordinates"":[[[127.4235169..."
1,가평군,2017,무단횡단사고다발지,6430775,2018045,4182025023,281141002,경기 가평2,경기도 가평군 가평읍(가평군농협 자라섬지점 부근),3,3,2,1,0,0,37.814267,127.514815,"{""type"":""Polygon"",""coordinates"":[[[127.5175100..."
2,가평군,2017,무단횡단사고다발지,6429445,2018045,4182032521,281141001,경기 가평1,경기도 가평군 청평면(종로약국 부근),4,4,0,0,1,3,37.737294,127.418783,"{""type"":""Polygon"",""coordinates"":[[[127.4214779..."
3,가평군,2017,보행노인사고다발지,6402864,2018029,4182025023,41820001,경기도 가평군1,경기도 가평군 가평읍(가평군농협하나로마트자라점 부근),3,3,2,1,0,0,37.813743,127.514905,"{""type"":""Polygon"",""coordinates"":[[[127.5167018..."
4,가평군,2016,자전거사고다발지,6302815,2017050,4182032522,41820001,경기도 가평군1,경기도 가평군 청평면(중감천교 부근),4,4,0,2,2,0,37.771986,127.451958,"{""type"":""Polygon"",""coordinates"":[[[127.4537544..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2033,화성시,2012,무단횡단사고다발지,167352,2013114,4159011600,411324005,경기 화성동부5,경기도 화성시 진안동((디지털프라자앞교차로) 부근),5,5,1,3,1,0,37.211550,127.036314,"{""type"":""Polygon"",""coordinates"":[[[127.038704,..."
2034,화성시,2012,보행어린이사고다발지,143380,2013097,4159011800,41590001,경기도 화성시1,경기도 화성시 능동((서해그랑블앞교차로) 부근),4,4,0,3,1,0,37.198866,127.072021,"{""type"":""Polygon"",""coordinates"":[[[127.0736144..."
2035,NaN,2013,보행노인사고다발지,196836,2014105,4173025000,41730001,경기도 여주군1,경기도 여주군 여주읍(홍문사거리 부근),5,5,0,5,0,0,37.296606,127.636983,"{""type"":""Polygon"",""coordinates"":[[[127.6385775..."
2036,NaN,2013,보행노인사고다발지,196837,2014105,4173031021,41730002,경기도 여주군2,경기도 여주군 점동면(점동중학교 인근),3,3,1,1,0,1,37.206433,127.662428,"{""type"":""Polygon"",""coordinates"":[[[127.6640215..."
2037,NaN,2013,보행어린이사고다발지,198405,2014110,4173025022,41730001,경기도 여주군1,경기도 여주군 여주읍(홍문사거리 부근),3,3,0,1,2,0,37.295550,127.637564,"{""type"":""Polygon"",""coordinates"":[[[127.6391594..."

In [4]:
df=df.drop(columns=['다발지식별자','다발지역그룹식별자','법정동코드','위치코드','사고다발지역폴리곤정보'])

In [5]:
df.head(7)

,시군명,사고년도,사고유형구분,시도시군구명,사고지역위치명,발생건수,사상자수,사망자수,중상자수,경상자수,부상자수,위도,경도
0,가평군,2018,보행노인사고다발지,경기도 가평군1,경기도 가평군 청평면(청평터미널 부근),4,4,0,2,2,0,37.739333,127.421720
1,가평군,2017,무단횡단사고다발지,경기 가평2,경기도 가평군 가평읍(가평군농협 자라섬지점 부근),3,3,2,1,0,0,37.814267,127.514815
2,가평군,2017,무단횡단사고다발지,경기 가평1,경기도 가평군 청평면(종로약국 부근),4,4,0,0,1,3,37.737294,127.418783
3,가평군,2017,보행노인사고다발지,경기도 가평군1,경기도 가평군 가평읍(가평군농협하나로마트자라점 부근),3,3,2,1,0,0,37.813743,127.514905
4,가평군,2016,자전거사고다발지,경기도 가평군1,경기도 가평군 청평면(중감천교 부근),4,4,0,2,2,0,37.771986,127.451958
5,가평군,2015,보행노인사고다발지,경기도 가평군1,경기도 가평군 가평읍(한국전력공사 부근),3,3,0,1,2,0,37.834295,127.511137
6,가평군,2013,보행노인사고다발지,경기도 가평군1,경기도 가평군 청평면((은성장) 부근),5,5,0,5,0,0,37.737810,127.419731

In [6]:
df.tail(7)

,시군명,사고년도,사고유형구분,시도시군구명,사고지역위치명,발생건수,사상자수,사망자수,중상자수,경상자수,부상자수,위도,경도
2031,화성시,2012,무단횡단사고다발지,경기 화성서부1,경기도 화성시 향남읍(평리교 부근),1,5,0,4,1,0,37.133308,126.910911
2032,화성시,2012,무단횡단사고다발지,경기 화성서부2,경기도 화성시 봉담읍((봉담새마을금고앞교차로) 부근),5,9,0,5,4,0,37.220980,126.949133
2033,화성시,2012,무단횡단사고다발지,경기 화성동부5,경기도 화성시 진안동((디지털프라자앞교차로) 부근),5,5,1,3,1,0,37.211550,127.036314
2034,화성시,2012,보행어린이사고다발지,경기도 화성시1,경기도 화성시 능동((서해그랑블앞교차로) 부근),4,4,0,3,1,0,37.198866,127.072021
2035,NaN,2013,보행노인사고다발지,경기도 여주군1,경기도 여주군 여주읍(홍문사거리 부근),5,5,0,5,0,0,37.296606,127.636983
2036,NaN,2013,보행노인사고다발지,경기도 여주군2,경기도 여주군 점동면(점동중학교 인근),3,3,1,1,0,1,37.206433,127.662428
2037,NaN,2013,보행어린이사고다발지,경기도 여주군1,경기도 여주군 여주읍(홍문사거리 부근),3,3,0,1,2,0,37.295550,127.637564

In [7]:
df=df.replace(0,np.NaN)

In [8]:
columns = df.columns
#list(columns)
pd.Series(columns)

0         시군명
1        사고년도
2      사고유형구분
3      시도시군구명
4     사고지역위치명
5        발생건수
6        사상자수
7        사망자수
8        중상자수
9        경상자수
10       부상자수
11         위도
12         경도
dtype: object

In [9]:
index = df.index
index

RangeIndex(start=0, stop=2038, step=1)

In [10]:
data = df.to_numpy()
data

array([['가평군', 2018, '보행노인사고다발지', ..., nan, 37.73933318, 127.4217204],
       ['가평군', 2017, '무단횡단사고다발지', ..., nan, 37.8142673, 127.5148151],
       ['가평군', 2017, '무단횡단사고다발지', ..., 3.0, 37.73729418, 127.418783],
       ...,
       [nan, 2013, '보행노인사고다발지', ..., nan, 37.29660626, 127.6369825],
       [nan, 2013, '보행노인사고다발지', ..., 1.0, 37.20643281, 127.6624283],
       [nan, 2013, '보행어린이사고다발지', ..., nan, 37.29555043, 127.6375643]],
      dtype=object)

In [11]:
df.dtypes.value_counts()

float64    6
object     4
int64      3
dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2038 entries, 0 to 2037
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   시군명      2035 non-null   object
 1   사고년도     2038 non-null   int64
 2   사고유형구분   2038 non-null   object
 3   시도시군구명   2038 non-null   object
 4   사고지역위치명  2038 non-null   object
 5   발생건수     2038 non-null   int64
 6   사상자수     2038 non-null   int64
 7   사망자수     398 non-null    float64
 8   중상자수     1838 non-null   float64
 9   경상자수     1704 non-null   float64
 10  부상자수     534 non-null    float64
 11  위도       2038 non-null   float64
 12  경도       2038 non-null   float64
dtypes: float64(6), int64(3), object(4)
memory usage: 207.1+ KB

## 기술통계

In [13]:
df.describe()

,사고년도,발생건수,사상자수,사망자수,중상자수,경상자수,부상자수,위도,경도
count,2038.000000,2038.000000,2038.000000,398.000000,1838.000000,1704.000000,534.000000,2038.000000,2038.000000
mean,2015.321394,4.661433,4.909715,1.160804,2.585963,2.404343,1.299625,37.433995,126.984869
std,2.500318,2.036533,2.195567,0.419033,1.623507,1.376851,0.597148,0.199989,0.173202
min,2012.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,36.969045,126.598540
25%,2013.000000,3.000000,4.000000,1.000000,1.000000,1.000000,1.000000,37.296596,126.824471
50%,2015.000000,4.000000,4.000000,1.000000,2.000000,2.000000,1.000000,37.403916,127.003320
75%,2017.000000,5.000000,6.000000,1.000000,3.000000,3.000000,1.000000,37.587045,127.108055
max,2020.000000,26.000000,26.000000,4.000000,22.000000,10.000000,4.000000,38.026898,127.662428

## 결측치

In [14]:
df.isna()

,시군명,사고년도,사고유형구분,시도시군구명,사고지역위치명,발생건수,사상자수,사망자수,중상자수,경상자수,부상자수,위도,경도
0,False,False,False,False,False,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,True,True,False,False
2,False,False,False,False,False,False,False,True,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,True,True,False,False
4,False,False,False,False,False,False,False,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2033,False,False,False,False,False,False,False,False,False,False,True,False,False
2034,False,False,False,False,False,False,False,True,False,False,True,False,False
2035,True,False,False,False,False,False,False,True,False,True,True,False,False
2036,True,False,False,False,False,False,False,False,False,True,False,False,False
2037,True,False,False,False,False,False,False,True,False,False,True,False,False

In [15]:
df.isna().sum()

시군명           3
사고년도          0
사고유형구분        0
시도시군구명        0
사고지역위치명       0
발생건수          0
사상자수          0
사망자수       1640
중상자수        200
경상자수        334
부상자수       1504
위도            0
경도            0
dtype: int64

In [16]:
df.fillna(0,inplace=True) # 사망자수~부상자수 NaN값을 0으로 채워넣기

In [17]:
# df.loc[2035:2037,:'시군명'=='여주군']

In [18]:
#geos['시군명'=0] == df['여주시']

In [19]:
#names.loc[len(names)] = ['NaN', ]
#na

NameError: name 'names' is not defined

In [ ]:
df.loc[2035:2037,:'시군명']

In [ ]:
# df.loc[2035:2037,:시군명=='여주시']

In [ ]:
# df.loc[df['시군명'] == 0, '시군명'] = '여주시'

# df

In [ ]:
df.shape

In [ ]:
df.size

In [ ]:
len(df)

In [ ]:
df.ndim

# 오류 수정

In [41]:
df.fillna('여주시')

,시군명,사고년도,사고유형구분,시도시군구명,사고지역위치명,발생건수,사상자수,사망자수,중상자수,경상자수,부상자수,위도,경도
0,가평군,2018,보행노인사고다발지,경기도 가평군1,경기도 가평군 청평면(청평터미널 부근),4,4,0.0,2,2,0,37.739333,127.421720
1,가평군,2017,무단횡단사고다발지,경기 가평2,경기도 가평군 가평읍(가평군농협 자라섬지점 부근),3,3,2.0,1,0,0,37.814267,127.514815
2,가평군,2017,무단횡단사고다발지,경기 가평1,경기도 가평군 청평면(종로약국 부근),4,4,0.0,0,1,3,37.737294,127.418783
3,가평군,2017,보행노인사고다발지,경기도 가평군1,경기도 가평군 가평읍(가평군농협하나로마트자라점 부근),3,3,2.0,1,0,0,37.813743,127.514905
4,가평군,2016,자전거사고다발지,경기도 가평군1,경기도 가평군 청평면(중감천교 부근),4,4,0.0,2,2,0,37.771986,127.451958
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2033,화성시,2012,무단횡단사고다발지,경기 화성동부5,경기도 화성시 진안동((디지털프라자앞교차로) 부근),5,5,1.0,3,1,0,37.211550,127.036314
2034,화성시,2012,보행어린이사고다발지,경기도 화성시1,경기도 화성시 능동((서해그랑블앞교차로) 부근),4,4,0.0,3,1,0,37.198866,127.072021
2035,0,2013,보행노인사고다발지,경기도 여주군1,경기도 여주군 여주읍(홍문사거리 부근),5,5,0.0,5,0,0,37.296606,127.636983
2036,0,2013,보행노인사고다발지,경기도 여주군2,경기도 여주군 점동면(점동중학교 인근),3,3,1.0,1,0,1,37.206433,127.662428
2037,0,2013,보행어린이사고다발지,경기도 여주군1,경기도 여주군 여주읍(홍문사거리 부근),3,3,0.0,1,2,0,37.295550,127.637564

In [42]:
df.loc[df['사고유형구분'] == '자전?', '사고유형구분'] = '자전거사고다발지'

df

,시군명,사고년도,사고유형구분,시도시군구명,사고지역위치명,발생건수,사상자수,사망자수,중상자수,경상자수,부상자수,위도,경도
0,가평군,2018,보행노인사고다발지,경기도 가평군1,경기도 가평군 청평면(청평터미널 부근),4,4,0.0,2,2,0,37.739333,127.421720
1,가평군,2017,무단횡단사고다발지,경기 가평2,경기도 가평군 가평읍(가평군농협 자라섬지점 부근),3,3,2.0,1,0,0,37.814267,127.514815
2,가평군,2017,무단횡단사고다발지,경기 가평1,경기도 가평군 청평면(종로약국 부근),4,4,0.0,0,1,3,37.737294,127.418783
3,가평군,2017,보행노인사고다발지,경기도 가평군1,경기도 가평군 가평읍(가평군농협하나로마트자라점 부근),3,3,2.0,1,0,0,37.813743,127.514905
4,가평군,2016,자전거사고다발지,경기도 가평군1,경기도 가평군 청평면(중감천교 부근),4,4,0.0,2,2,0,37.771986,127.451958
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2033,화성시,2012,무단횡단사고다발지,경기 화성동부5,경기도 화성시 진안동((디지털프라자앞교차로) 부근),5,5,1.0,3,1,0,37.211550,127.036314
2034,화성시,2012,보행어린이사고다발지,경기도 화성시1,경기도 화성시 능동((서해그랑블앞교차로) 부근),4,4,0.0,3,1,0,37.198866,127.072021
2035,0,2013,보행노인사고다발지,경기도 여주군1,경기도 여주군 여주읍(홍문사거리 부근),5,5,0.0,5,0,0,37.296606,127.636983
2036,0,2013,보행노인사고다발지,경기도 여주군2,경기도 여주군 점동면(점동중학교 인근),3,3,1.0,1,0,1,37.206433,127.662428
2037,0,2013,보행어린이사고다발지,경기도 여주군1,경기도 여주군 여주읍(홍문사거리 부근),3,3,0.0,1,2,0,37.295550,127.637564

In [43]:
df['사고유형구분']

0        보행노인사고다발지
1        무단횡단사고다발지
2        무단횡단사고다발지
3        보행노인사고다발지
4         자전거사고다발지
           ...
2033     무단횡단사고다발지
2034    보행어린이사고다발지
2035     보행노인사고다발지
2036     보행노인사고다발지
2037    보행어린이사고다발지
Name: 사고유형구분, Length: 2038, dtype: object

In [44]:
df.loc[df['사고유형구분'] == '보헹노', '사고유형구분'] = '보행노인사고다발지'

df

,시군명,사고년도,사고유형구분,시도시군구명,사고지역위치명,발생건수,사상자수,사망자수,중상자수,경상자수,부상자수,위도,경도
0,가평군,2018,보행노인사고다발지,경기도 가평군1,경기도 가평군 청평면(청평터미널 부근),4,4,0.0,2,2,0,37.739333,127.421720
1,가평군,2017,무단횡단사고다발지,경기 가평2,경기도 가평군 가평읍(가평군농협 자라섬지점 부근),3,3,2.0,1,0,0,37.814267,127.514815
2,가평군,2017,무단횡단사고다발지,경기 가평1,경기도 가평군 청평면(종로약국 부근),4,4,0.0,0,1,3,37.737294,127.418783
3,가평군,2017,보행노인사고다발지,경기도 가평군1,경기도 가평군 가평읍(가평군농협하나로마트자라점 부근),3,3,2.0,1,0,0,37.813743,127.514905
4,가평군,2016,자전거사고다발지,경기도 가평군1,경기도 가평군 청평면(중감천교 부근),4,4,0.0,2,2,0,37.771986,127.451958
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2033,화성시,2012,무단횡단사고다발지,경기 화성동부5,경기도 화성시 진안동((디지털프라자앞교차로) 부근),5,5,1.0,3,1,0,37.211550,127.036314
2034,화성시,2012,보행어린이사고다발지,경기도 화성시1,경기도 화성시 능동((서해그랑블앞교차로) 부근),4,4,0.0,3,1,0,37.198866,127.072021
2035,0,2013,보행노인사고다발지,경기도 여주군1,경기도 여주군 여주읍(홍문사거리 부근),5,5,0.0,5,0,0,37.296606,127.636983
2036,0,2013,보행노인사고다발지,경기도 여주군2,경기도 여주군 점동면(점동중학교 인근),3,3,1.0,1,0,1,37.206433,127.662428
2037,0,2013,보행어린이사고다발지,경기도 여주군1,경기도 여주군 여주읍(홍문사거리 부근),3,3,0.0,1,2,0,37.295550,127.637564

In [ ]:
df

In [ ]:
df['사고유형구분']

## memory_usage

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2038 entries, 0 to 2037
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   시군명      2038 non-null   object
 1   사고년도     2038 non-null   int64
 2   사고유형구분   2038 non-null   object
 3   시도시군구명   2038 non-null   object
 4   사고지역위치명  2038 non-null   object
 5   발생건수     2038 non-null   int64
 6   사상자수     2038 non-null   int64
 7   사망자수     2038 non-null   float64
 8   중상자수     2038 non-null   float64
 9   경상자수     2038 non-null   float64
 10  부상자수     2038 non-null   float64
 11  위도       2038 non-null   float64
 12  경도       2038 non-null   float64
dtypes: float64(6), int64(3), object(4)
memory usage: 207.1+ KB

In [21]:
df.dtypes

시군명         object
사고년도         int64
사고유형구분      object
시도시군구명      object
사고지역위치명     object
발생건수         int64
사상자수         int64
사망자수       float64
중상자수       float64
경상자수       float64
부상자수       float64
위도         float64
경도         float64
dtype: object

In [22]:
df.memory_usage(deep=True)

Index         128
시군명        179568
사고년도        16304
사고유형구분     200548
시도시군구명     207458
사고지역위치명    269622
발생건수        16304
사상자수        16304
사망자수        16304
중상자수        16304
경상자수        16304
부상자수        16304
위도          16304
경도          16304
dtype: int64

In [23]:
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

In [24]:
np.iinfo(np.int16)

iinfo(min=-32768, max=32767, dtype=int16)

In [25]:
df['사고유형구분'] = df['사고유형구분'].astype('object')
df.memory_usage(deep=True)

Index         128
시군명        179568
사고년도        16304
사고유형구분     200548
시도시군구명     207458
사고지역위치명    269622
발생건수        16304
사상자수        16304
사망자수        16304
중상자수        16304
경상자수        16304
부상자수        16304
위도          16304
경도          16304
dtype: int64

In [26]:
df['발생건수'] = df['발생건수'].astype(np.int8)

In [27]:
df.memory_usage(deep=True)

Index         128
시군명        179568
사고년도        16304
사고유형구분     200548
시도시군구명     207458
사고지역위치명    269622
발생건수         2038
사상자수        16304
사망자수        16304
중상자수        16304
경상자수        16304
부상자수        16304
위도          16304
경도          16304
dtype: int64

In [28]:
df['사상자수'] = df['사상자수'].astype(np.int8)

In [29]:
df.memory_usage(deep=True)

Index         128
시군명        179568
사고년도        16304
사고유형구분     200548
시도시군구명     207458
사고지역위치명    269622
발생건수         2038
사상자수         2038
사망자수        16304
중상자수        16304
경상자수        16304
부상자수        16304
위도          16304
경도          16304
dtype: int64

In [30]:
df['중상자수'] = df['중상자수'].astype(np.int8)

In [31]:
df.memory_usage(deep=True)

Index         128
시군명        179568
사고년도        16304
사고유형구분     200548
시도시군구명     207458
사고지역위치명    269622
발생건수         2038
사상자수         2038
사망자수        16304
중상자수         2038
경상자수        16304
부상자수        16304
위도          16304
경도          16304
dtype: int64

In [32]:
df['경상자수'] = df['경상자수'].astype(np.int8)

In [33]:
df.memory_usage(deep=True)

Index         128
시군명        179568
사고년도        16304
사고유형구분     200548
시도시군구명     207458
사고지역위치명    269622
발생건수         2038
사상자수         2038
사망자수        16304
중상자수         2038
경상자수         2038
부상자수        16304
위도          16304
경도          16304
dtype: int64

In [34]:
df['부상자수'] = df['부상자수'].astype(np.int8)

In [35]:
df.memory_usage(deep=True)

Index         128
시군명        179568
사고년도        16304
사고유형구분     200548
시도시군구명     207458
사고지역위치명    269622
발생건수         2038
사상자수         2038
사망자수        16304
중상자수         2038
경상자수         2038
부상자수         2038
위도          16304
경도          16304
dtype: int64

In [36]:
df['시군명'] = df['시군명'].astype('object')
df.memory_usage(deep=True)

Index         128
시군명        179568
사고년도        16304
사고유형구분     200548
시도시군구명     207458
사고지역위치명    269622
발생건수         2038
사상자수         2038
사망자수        16304
중상자수         2038
경상자수         2038
부상자수         2038
위도          16304
경도          16304
dtype: int64

In [37]:
df.memory_usage(deep=True)

Index         128
시군명        179568
사고년도        16304
사고유형구분     200548
시도시군구명     207458
사고지역위치명    269622
발생건수         2038
사상자수         2038
사망자수        16304
중상자수         2038
경상자수         2038
부상자수         2038
위도          16304
경도          16304
dtype: int64

# ---------------------------------------------------------------

In [ ]:
# df.select_dtypes(include=['object']).nunique()

In [ ]:
# df.memory_usage(deep=True)

In [ ]:
# df.index

## 최대 중 최소, 최소 중 최대 - nsmallest, nlargest

In [45]:
df1=df[['사고년도','사고유형구분','시도시군구명','발생건수']]
df1.head()

   사고년도     사고유형구분    시도시군구명  발생건수
0  2018  보행노인사고다발지  경기도 가평군1     4
1  2017  무단횡단사고다발지    경기 가평2     3
2  2017  무단횡단사고다발지    경기 가평1     4
3  2017  보행노인사고다발지  경기도 가평군1     3
4  2016   자전거사고다발지  경기도 가평군1     4

In [46]:
df1.nlargest(50,'사고년도').head(11)

     사고년도    사고유형구분         시도시군구명  발생건수
10   2020       보행노  경기도 고양시 일산동구1     5
11   2020       보행노  경기도 고양시 일산서구3     2
12   2020       보행노  경기도 고양시 일산서구2     3
13   2020       보행노   경기도 고양시 덕양구1     3
14   2020       보행노  경기도 고양시 일산서구4     2
15   2020       보행노  경기도 고양시 일산동구2     3
16   2020       보행노  경기도 고양시 일산서구1     4
17   2020  자전거사고다발지  경기도 고양시 일산동구2     4
18   2020  자전거사고다발지  경기도 고양시 일산동구1     4
19   2020  자전거사고다발지   경기도 고양시 덕양구1     4
166  2020       보행노       경기도 과천시1     2

In [47]:
# 사고유형을 기준으로 정렬하기
(
    df[['사고년도','사고유형구분','시도시군구명','발생건수']]
.sort_values('사고유형구분',ascending=True)
)

      사고년도     사고유형구분        시도시군구명  발생건수
1018  2013  무단횡단사고다발지      경기 수원서부1    23
1431  2015  무단횡단사고다발지  경기도 안양시 동안구2    10
1432  2015  무단횡단사고다발지  경기도 안양시 동안구1    11
1451  2014  무단횡단사고다발지      경기 안양만안1     4
1452  2014  무단횡단사고다발지      경기 안양만안2     4
...    ...        ...           ...   ...
1387  2014   자전거사고다발지      경기도 안성시1     5
573   2014   자전거사고다발지  경기도 부천시 원미구5     8
572   2014   자전거사고다발지  경기도 부천시 원미구4     9
570   2014   자전거사고다발지  경기도 부천시 원미구2    10
1467  2014   자전거사고다발지  경기도 안양시 동안구7     5

[2038 rows x 4 columns]

In [48]:
(
    df[['사고년도','사고유형구분','시도시군구명','발생건수']]
.sort_values('사고유형구분',ascending=False)
)

      사고년도     사고유형구분         시도시군구명  발생건수
562   2014   자전거사고다발지  경기도 부천시 원미구12     5
1473  2014   자전거사고다발지   경기도 안양시 동안구1     7
1471  2014   자전거사고다발지  경기도 안양시 동안구11     4
1470  2014   자전거사고다발지  경기도 안양시 동안구10     4
674   2018   자전거사고다발지   경기도 성남시 분당구1     7
...    ...        ...            ...   ...
616   2012  무단횡단사고다발지       경기 부천원미2     4
617   2012  무단횡단사고다발지       경기 부천원미1     4
1518  2015  무단횡단사고다발지       경기도 양주시1     4
618   2012  무단횡단사고다발지       경기 부천오정3     6
1019  2013  무단횡단사고다발지       경기 수원남부3     4

[2038 rows x 4 columns]

## 데이터 딕셔너리

In [49]:
pd.read_csv('C:\\Users\\kim a hyun\\Desktop\\사고다발지현황.csv',encoding='cp949',index_col=0)

,사고년도,사고유형구분,다발지식별자,다발지역그룹식별자,법정동코드,위치코드,시도시군구명,사고지역위치명,발생건수,사상자수,사망자수,중상자수,경상자수,부상자수,위도,경도,사고다발지역폴리곤정보
시군명,,,,,,,,,,,,,,,,,
가평군,2018,보행노인사고다발지,6506068,2019036,4182032521,41820001,경기도 가평군1,경기도 가평군 청평면(청평터미널 부근),4,4,0,2,2,0,37.739333,127.421720,"{""type"":""Polygon"",""coordinates"":[[[127.4235169..."
가평군,2017,무단횡단사고다발지,6430775,2018045,4182025023,281141002,경기 가평2,경기도 가평군 가평읍(가평군농협 자라섬지점 부근),3,3,2,1,0,0,37.814267,127.514815,"{""type"":""Polygon"",""coordinates"":[[[127.5175100..."
가평군,2017,무단횡단사고다발지,6429445,2018045,4182032521,281141001,경기 가평1,경기도 가평군 청평면(종로약국 부근),4,4,0,0,1,3,37.737294,127.418783,"{""type"":""Polygon"",""coordinates"":[[[127.4214779..."
가평군,2017,보행노인사고다발지,6402864,2018029,4182025023,41820001,경기도 가평군1,경기도 가평군 가평읍(가평군농협하나로마트자라점 부근),3,3,2,1,0,0,37.813743,127.514905,"{""type"":""Polygon"",""coordinates"":[[[127.5167018..."
가평군,2016,자전거사고다발지,6302815,2017050,4182032522,41820001,경기도 가평군1,경기도 가평군 청평면(중감천교 부근),4,4,0,2,2,0,37.771986,127.451958,"{""type"":""Polygon"",""coordinates"":[[[127.4537544..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
화성시,2012,무단횡단사고다발지,167352,2013114,4159011600,411324005,경기 화성동부5,경기도 화성시 진안동((디지털프라자앞교차로) 부근),5,5,1,3,1,0,37.211550,127.036314,"{""type"":""Polygon"",""coordinates"":[[[127.038704,..."
화성시,2012,보행어린이사고다발지,143380,2013097,4159011800,41590001,경기도 화성시1,경기도 화성시 능동((서해그랑블앞교차로) 부근),4,4,0,3,1,0,37.198866,127.072021,"{""type"":""Polygon"",""coordinates"":[[[127.0736144..."
NaN,2013,보행노인사고다발지,196836,2014105,4173025000,41730001,경기도 여주군1,경기도 여주군 여주읍(홍문사거리 부근),5,5,0,5,0,0,37.296606,127.636983,"{""type"":""Polygon"",""coordinates"":[[[127.6385775..."
NaN,2013,보행노인사고다발지,196837,2014105,4173031021,41730002,경기도 여주군2,경기도 여주군 점동면(점동중학교 인근),3,3,1,1,0,1,37.206433,127.662428,"{""type"":""Polygon"",""coordinates"":[[[127.6640215..."
NaN,2013,보행어린이사고다발지,198405,2014110,4173025022,41730001,경기도 여주군1,경기도 여주군 여주읍(홍문사거리 부근),3,3,0,1,2,0,37.295550,127.637564,"{""type"":""Polygon"",""coordinates"":[[[127.6391594..."